export const UsersRoutes = ["/users"];
export const CoursesRoutes = ["/courses"];
export const OffersRoutes = ["/offers"];
export const CategoryRoutes = ["/category"];
export const SyllabusRoutes = ["/syllabus"];
export const CarreerRoutes = ["/admincareers"];
export const CertificateRoutes = ["/certificate"];
export const DashboardRoutes = ["/dashboard"];
export const PaymentRoutes = ["/payment-settings", "/payment-management"];