export const apiUrls = {
  login: "login",
  signUp: "register",
  verifyOtp: "verify-otp",
  getUsers: "users",
  updateUser: "user",
  changePassword: "user/change-password",
  offers: "offers",
  carrers: "careers",
  carrersStatus: "careersstatus",
  courses: "courses",
  contact: "contact",
  lessonsNew: "lessons/course",
  category: "category",
  lessons: "lessons",
  reviews: "reviews",
  dashboardCounts: "dashboard-counts",
  forgotPassword: "forgot-password",
  resetPassword: "reset-password",
  coursesMail: "course-mail",
  carrerMail: "career-mail",
  categoryMail: "category-mail",
};
