const mongoose = require("mongoose");

const studentAssignmentSchema = new mongoose.Schema({
    student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    itemType: {
        type: String,
        enum: ["course", "internship", "project"],
        required: true
    },
    itemId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        refPath: 'itemModel'
    },
    itemModel: {
        type: String,
        required: true,
        enum: ['Course', 'Internship', 'Project']
    },
    progress: {
        type: Number,
        default: 0,
        min: 0,
        max: 100
    },

    // ===== PROJECT WORKFLOW FIELDS =====

    // Status for all types + extended project statuses
    status: {
        type: String,
        enum: [
            "assigned",                    // Initial state
            "requirement-submitted",       // Student/Admin submitted requirements
            "advance-payment-pending",     // Admin requests advance
            "in-progress",                 // Advance paid, work started
            "ready-for-demo",              // Work done, waiting for demo
            "final-payment-pending",       // Demo done, requesting final payment
            "ready-for-download",          // Final payment done, files uploaded
            "delivered",                   // Student downloaded / Admin marked
            "completed"                    // Legacy/archive
        ],
        default: "assigned"
    },

    // Requirement Submission (by student OR admin)
    requirementSubmission: {
        topic: { type: String },
        projectType: {
            type: String,
            enum: ["website", "mobile-app", "report", "ppt", "research", "code", "design", "other"]
        },
        collegeGuidelines: { type: String },
        notes: { type: String },
        attachments: [{
            fileName: String,
            filePath: String,
            uploadedAt: { type: Date, default: Date.now }
        }],
        submittedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },
        submittedByRole: {
            type: String,
            enum: ["student", "admin"]
        },
        submittedAt: { type: Date }
    },

    // Admin Review
    adminReview: {
        reviewedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },
        reviewedAt: { type: Date },
        notes: { type: String },
        approved: { type: Boolean }
    },

    // Payment Tracking (Optional)
    payment: {
        required: { type: Boolean, default: false },
        amount: { type: Number, default: 0 },
        advanceAmount: { type: Number, default: 0 }, // Store fixed advance
        finalAmount: { type: Number, default: 0 },   // Store fixed final
        status: {
            type: String,
            enum: ["not-required", "pending", "paid", "waived"],
            default: "not-required"
        },
        paidAt: { type: Date },
        notes: { type: String },
        // Payment Proof fields
        paymentMethod: {
            type: String,
            enum: ["upi", "bank-transfer", "cash", "other"]
        },
        proofFile: { type: String }, // URL to uploaded proof
        proofUploadedAt: { type: Date },
        transactionId: { type: String }
    },

    // Invoice (Generated by Admin)
    invoice: {
        url: { type: String },              // B2 URL to PDF
        invoiceNumber: { type: String },    // INV-2024-ABCDEF
        generatedAt: { type: Date },
        generatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        }
    },

    // Delivery Files (Admin uploads for student to download)
    deliveryFiles: [{
        fileName: { type: String, required: true },
        filePath: { type: String, required: true },
        fileType: {
            type: String,
            enum: ["project-file", "report", "ppt", "source-code", "documentation", "video", "learning-material", "other"]
        },
        uploadedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },
        uploadedAt: { type: Date, default: Date.now }
    }],

    // Student Feedback
    feedback: {
        rating: { type: Number, min: 1, max: 5 },
        comments: { type: String },
        submittedAt: { type: Date }
    },

    // Reference to the Project Submission document
    submission: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Submission"
    },

    // ===== COURSE WORKFLOW FIELDS =====

    // Course Submissions (Student uploads or Admin on behalf)
    courseSubmissions: [{
        fileName: { type: String, required: true },
        filePath: { type: String, required: true },
        uploadedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },
        uploadedByRole: {
            type: String,
            enum: ["student", "admin"]
        },
        uploadedAt: { type: Date, default: Date.now },
        notes: { type: String }
    }],

    // Certificate (Issued by Admin)
    certificate: {
        url: { type: String }, // Path to uploaded certificate file
        issuedAt: { type: Date },
        issuedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        }
    },

    // Timestamps
    assignedAt: {
        type: Date,
        default: Date.now
    },
    completedAt: {
        type: Date
    },
    assignedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User"
    }
});

// Index for efficient queries
studentAssignmentSchema.index({ student: 1, itemType: 1 });
studentAssignmentSchema.index({ student: 1, itemId: 1 }, { unique: true });
studentAssignmentSchema.index({ status: 1 });

module.exports = mongoose.model("StudentAssignment", studentAssignmentSchema);
